### ISSUE TITLE
Textures sometimes break

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/CTM-Resources#5]
Sometimes the textures show up as missing textures. I'm sure that this problem is caused by Optifine, but I don't know how to fix it without removing Optifine. I've disabled connected textures on Optifine, yet the textures sometimes still show as missing.

**Comment by ChloeDawn** [comment]
This issue actually is caused by CTM, the original repository you reported to. The bug is fixed but a release hasn't been pushed yet.

**Comment by tterrag1098** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/54

**Comment by ghost** [comment]
Oh, better wait for the new release then. Do you have a set release date?

**Comment by ZombieHDGaming** [comment]
Yes, about over an hour ago.
